---
# handlers file for .
- name: Restart Postgresql
  systemd:
    name: postgresql
    state: restarted

# - name: Start Postgresql
#   systemd:
#     name: postgresql
#     state: started

# - name: Stop Postgresql
#   systemd:
#     name: postgresql
#     state: stopped

- name: Enable Postgresql
  systemd:
    name: postgresql
    enabled: yes

- name: Restart sonar
  service:
    name: sonar
    state: restarted